#!/usr/bin/env bash
# Copyright 2012 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

# Exit immediately if a command exits with a non-zero status.
set -o errexit
# Treat unset variables as an error when substituting.
set -o nounset

# Exec log service for the MaaS API and Web UI Server.
logdir="../../../logs/api" && mkdir -p "${logdir}"
# Rotate when logs reach 1MB, keeping no more than 10.
exec multilog s1048576 n10 "${logdir}"
