#!/bin/sh

infile="${1}"
program="$2"
replace="${3:-__LATE_COMMAND__}"
base64=$(base64 --wrap 0 "${program}")
# the '&' have to be escaped through sed
str='f=$1; shift ; echo $0 | base64 --decode > "$f" \&\& chmod u+x "$f" \&\& "$f" "$@"'
sed -e "s,$replace,in-target sh -c '$str' ${base64} /root/late-command," "${infile}" 
