#!/usr/bin/env bash
# Copyright 2012 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

# Exit immediately if a command exits with a non-zero status.
set -o errexit
# Treat unset variables as an error when substituting.
set -o nounset

# Move to the project root.
cd "$(dirname "$0")/../.."

# Start logging, if requested. Not using multilog here right now
# because there are race issues when restarting.
[ -z "${logdir:-}" ] || exec &>> "${logdir}/current"

# Simulate what the package does:
# - generate a uuid
# - create a maas_local_celeryconfig.py file with CLUSTER_UUID=$uuid and
#   make sure that file is on the path.
# - run bin/maas-provision start-cluster-controller
local_config="run/cluster-worker/maas_local_celeryconfig.py"
if [ ! -f $local_config ];
then
uuid=`uuidgen`
mkdir -p run/cluster-worker/
cat <<EOF > "$local_config"
CLUSTER_UUID='$uuid'
EOF
fi
export PYTHONPATH=run/cluster-worker/:etc/:src/
export CELERY_CONFIG_MODULE=democeleryconfig_cluster
script="$(readlink -f bin/maas-provision)"
exec fghack "${script}" start-cluster-controller http://0.0.0.0:5240/
