#!/usr/bin/env bash
# Copyright 2012 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

# Exit immediately if a command exits with a non-zero status.
set -o errexit
# Treat unset variables as an error when substituting.
set -o nounset

# Move to the project root.
cd "$(dirname "$0")/../.."

# Start logging, if requested. Not using multilog here right now
# because there are race issues when restarting.
[ -z "${logdir:-}" ] || exec &>> "${logdir}/current"

# XXX rvb 2012-09-27: Simulate what the package does:
# - generate a uuid
# - create a maas_local_celeryconfig.py file with CLUSTER_UUID=$uuid and
#   make sure that file is on the path.
# - define: script="$(readlink -f bin/maas-provision)"
# - call: exec "${script}" start-cluster-controller http://0.0.0.0:5240/
# XXX Remove this once the call to
# /bin/maas-provision start-cluster-controller is in place.
script="$(readlink -f bin/celeryd)"
exec fghack "${script}" \
    --loglevel INFO --beat --queues demo-UUID \
    --config democeleryconfig_cluster
