#!/usr/bin/env bash
# Copyright 2012 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

# Exit immediately if a command exits with a non-zero status.
set -o errexit
# Treat unset variables as an error when substituting.
set -o nounset

# Move to the project root.
cd ../..

# Exec the MaaS API and Web UI Server.
script="$(readlink -f bin/maas)"
# Django's automatic reloader interferes with daemontools.
exec "${script}" runserver 8000 --settings=maas.demo --noreload
