#!/usr/bin/env python2.7
# Copyright 2012 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

"""Generate and write out a configuration for a DHCP server."""

# In a development environment, run this with bin/py to set the PYTHONPATH.

from __future__ import (
    absolute_import,
    print_function,
    unicode_literals,
    )

__metaclass__ = type


from argparse import ArgumentParser
import sys

from provisioningserver.dhcp import writer

parser = ArgumentParser(__doc__)
writer.add_arguments(parser)
args = parser.parse_args(sys.argv[1:])
writer.run(args)
