#!/usr/bin/env bash
# Copyright 2012 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

# Exit immediately if a command exits with a non-zero status.
set -o errexit
# Treat unset variables as an error when substituting.
set -o nounset

# Move to the project root.
cd ../..

# Start logging, if requested. Not using multilog here right now
# because there are race issues when restarting.
[ -z "${logdir:-}" ] || exec &>> "${logdir}/current"

# Load common functions.
source "services/functions"

# The port should match the port set in etc/pserv.yaml, or be the
# default port for pserv.
wait_until_socket_closed "localhost" "5241"

# Exec the Provisioning Server.
script="$(readlink -f bin/twistd.pserv)"
config="$(readlink -f etc/pserv.yaml)"
exec "${script}" --nodaemon --pidfile="" maas-pserv --config-file "${config}"
