#!/usr/bin/env bash
# Copyright 2012 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

# Exit immediately if a command exits with a non-zero status.
set -o errexit
# Treat unset variables as an error when substituting.
set -o nounset

# Move to the project root.
cd ../..

# Start logging, if requested.
[ -z "${logdir:-}" ] || exec &> >(
    exec multilog s1048576 n10 "${logdir}")

# Exec the Provisioning Server.
script="$(readlink -f bin/twistd.pserv)"
config="$(readlink -f etc/pserv.yaml)"
exec "${script}" --nodaemon maas-pserv --config-file "${config}"
